#!/usr/bin/env lua

--[[
===========================================
🔍 Roblox/Rojo Luau Project Audit (v2.0)
===========================================
Usage: roblox-audit
===========================================
]]

-- Cross-platform helpers
local IS_WINDOWS = package.config:sub(1, 1) == "\\"
local NULL_DEVICE = IS_WINDOWS and "NUL" or "/dev/null"
local PATH_SEP = IS_WINDOWS and "\\" or "/"

-- Use standard lua runtime
local LUA_CMD = "lua"

-- Import companion modules
-- When bundled with darklua, these will be embedded in this file
-- When run unbundled, they need to be in the same directory
local analyzeDeps = require("analyze-dependencies")
local visualizeDeps = require("visualize-dependencies")

local function commandExists(cmd)
	local handle = io.popen(cmd .. " --version 2>" .. NULL_DEVICE)
	if not handle then
		return false
	end
	handle:close()
	return true
end

local function dirExists(path)
	-- Try to list directory
	local handle = IS_WINDOWS and io.popen("dir " .. path .. " 2>" .. NULL_DEVICE)
		or io.popen("ls -d " .. path .. " 2>" .. NULL_DEVICE)
	if not handle then
		return false
	end
	local result = handle:read("*a")
	handle:close()
	return result ~= ""
end

local function findFiles(dir, pattern)
	local cmd = IS_WINDOWS and string.format('dir /s /b "%s\\%s" 2>%s', dir, pattern, NULL_DEVICE)
		or string.format('find "%s" -name "%s" 2>%s', dir, pattern, NULL_DEVICE)

	local handle = io.popen(cmd)
	if not handle then
		return 0
	end

	local count = 0
	for _ in handle:lines() do
		count = count + 1
	end
	handle:close()
	return count
end

local function exec(cmd, outputFile)
	if outputFile then
		local fullCmd = cmd .. " > " .. outputFile .. " 2>&1"
		return os.execute(fullCmd)
	else
		return os.execute(cmd)
	end
end

local function grepCount(file, pattern)
	local handle = io.open(file, "r")
	if not handle then
		return 0
	end

	local count = 0
	for line in handle:lines() do
		if line:match(pattern) then
			count = count + 1
		end
	end
	handle:close()
	return count
end

local function grepExists(file, pattern)
	return grepCount(file, pattern) > 0
end

local function fileExists(path)
	local file = io.open(path, "r")
	if file then
		file:close()
		return true
	end
	return false
end

local function writeFile(path, content)
	local file = io.open(path, "w")
	if not file then
		return false
	end
	file:write(content)
	file:close()
	return true
end

-- -------------------------------------------
-- Auto-Initialize Configuration Files
-- -------------------------------------------
local function ensureConfigsExist()
	local created = false

	-- selene.toml
	if not fileExists("selene.toml") then
		local seleneConfig = [[# Selene - Lua/Luau linter configuration
# https://kampfkarren.github.io/selene/
# Auto-generated by roblox-audit

# Use Roblox standard library (enables 'game', 'workspace', 'task', etc.)
std = "roblox"

[config]
# Enable Luau syntax support (continue, compound assignments, etc.)
luau = true
]]
		if writeFile("selene.toml", seleneConfig) then
			print("📝 Created selene.toml (auto-initialized)")
			created = true
		end
	end

	-- stylua.toml
	if not fileExists("stylua.toml") then
		local styluaConfig = [[# StyLua - Luau code formatter configuration
# https://github.com/JohnnyMorganz/StyLua
# Auto-generated by roblox-audit

column_width = 100
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 4
quote_style = "AutoPreferDouble"

# Disable automatic require() sorting (optional)
[sort_requires]
enabled = false
]]
		if writeFile("stylua.toml", styluaConfig) then
			print("📝 Created stylua.toml (auto-initialized)")
			created = true
		end
	end

	if created then
		print("")
	end
end

-- Initialize configs before running audit
ensureConfigsExist()

print("📍 Project: Roblox/Rojo (Luau)")

-- Detect source directory (prefer src/ over sync/)
local SRC_DIR = "src"
if not dirExists("src") then
	if dirExists("sync") then
		SRC_DIR = "sync"
	else
		SRC_DIR = "."
	end
end

print("📂 Source: " .. SRC_DIR .. "/")
print("")
print("🚀 Starting audit...")
print("")

-- Create audit directory
os.execute("mkdir audit 2>" .. NULL_DEVICE)

-- -------------------------------------------
-- 1. File Tree
-- -------------------------------------------
print("📁 Generating file tree...")
if commandExists("tree") then
	local ignorePattern = IS_WINDOWS and "" or "-I 'node_modules|.git|build|out|Packages|DevPackages|audit'"
	exec("tree " .. ignorePattern .. " --dirsfirst -a", "audit/audit-tree.txt")
	print("   ✓ audit/audit-tree.txt")
else
	print("   ⏭️  Skipped (tree not installed)")
	if IS_WINDOWS then
		print("      💡 choco install tree")
	else
		print("      💡 brew install tree")
	end
end

-- -------------------------------------------
-- 2. Rojo Sourcemap
-- -------------------------------------------
print("🗺️  Generating Rojo sourcemap...")
if commandExists("rojo") then
	-- Find .project.json file
	local findCmd = IS_WINDOWS and 'dir /b *.project.json 2>' .. NULL_DEVICE
		or 'find . -maxdepth 1 -name "*.project.json" 2>' .. NULL_DEVICE

	local handle = io.popen(findCmd)
	if handle then
		local projectFile = handle:read("*l")
		handle:close()

		if projectFile and projectFile ~= "" then
			-- Clean up path for Windows
			if IS_WINDOWS then
				projectFile = projectFile:match("^%s*(.-)%s*$") -- trim whitespace
			end

			exec('rojo sourcemap "' .. projectFile .. '" --output sourcemap.json', NULL_DEVICE)
			print("   ✓ sourcemap.json (from " .. projectFile .. ")")
		else
			print("   ⚠️  No .project.json found")
		end
	end
else
	print("   ⏭️  Skipped (rojo not installed)")
	print("      💡 rokit install")
end

-- -------------------------------------------
-- 3. Type Checking (luau-lsp)
-- -------------------------------------------
print("🔍 Running luau-lsp analyze...")
if commandExists("luau-lsp") then
	local sourcemapFlag = io.open("sourcemap.json", "r") and "--sourcemap=sourcemap.json" or ""
	if sourcemapFlag ~= "" then
		io.close(io.open("sourcemap.json", "r"))
	end

	exec('luau-lsp analyze ' .. sourcemapFlag .. ' "' .. SRC_DIR .. '/"', "audit/audit-check.txt")

	if grepExists("audit/audit-check.txt", "error:") or grepExists("audit/audit-check.txt", "TypeError:") then
		local errorCount = grepCount("audit/audit-check.txt", "error:") + grepCount("audit/audit-check.txt", "TypeError:")
		print("   ⚠️  audit/audit-check.txt (" .. errorCount .. " type errors found)")
	else
		print("   ✓ audit/audit-check.txt (no errors 🎉)")
	end
else
	print("   ⏭️  Skipped (luau-lsp not installed)")
	print("      💡 rokit install")
end

-- -------------------------------------------
-- 4. Selene Linting
-- -------------------------------------------
print("🔎 Running Selene...")
if commandExists("selene") then
	exec('selene "' .. SRC_DIR .. '/"', "audit/audit-selene.txt")

	if grepExists("audit/audit-selene.txt", "Could not collect standard library") then
		print("   ❌ audit/audit-selene.txt (Selene stdlib error)")
		print("      ⚠️  Selene 0.27.1 has a bug with Roblox stdlib")
	elseif grepExists("audit/audit-selene.txt", "^Results:") then
		local warnings = grepCount("audit/audit-selene.txt", "warning")
		local errors = grepCount("audit/audit-selene.txt", "error")

		if errors > 0 then
			print(string.format("   ⚠️  audit/audit-selene.txt (%d errors, %d warnings)", errors, warnings))
		elseif warnings > 0 then
			print(string.format("   ⚠️  audit/audit-selene.txt (%d warnings)", warnings))
		else
			print("   ✓ audit/audit-selene.txt (no issues 🎉)")
		end
	else
		print("   ✓ audit/audit-selene.txt (no issues 🎉)")
	end
else
	print("   ⏭️  Skipped (selene not installed)")
	print("      💡 rokit install")
end

-- -------------------------------------------
-- 5. Style Check (StyLua)
-- -------------------------------------------
print("🎨 Checking code style...")
if commandExists("stylua") then
	local result = exec('stylua --check "' .. SRC_DIR .. '/"', "audit/audit-style.txt")

	if result == 0 or result == true then
		print("   ✓ audit/audit-style.txt (formatted correctly 🎉)")
	else
		if grepExists("audit/audit-style.txt", "error parsing") then
			local parseErrors = grepCount("audit/audit-style.txt", "error parsing")
			print("   ⚠️  audit/audit-style.txt (" .. parseErrors .. " parse errors)")
			print("      💡 StyLua doesn't support single-line 'continue' yet")
		else
			local diffCount = grepCount("audit/audit-style.txt", "^Diff in")
			if diffCount > 0 then
				print("   ⚠️  audit/audit-style.txt (" .. diffCount .. " files need formatting)")
			else
				print("   ⚠️  audit/audit-style.txt (has issues)")
			end
		end
	end
else
	print("   ⏭️  Skipped (stylua not installed)")
	print("      💡 rokit install")
end

-- -------------------------------------------
-- 6. Circular Dependencies
-- -------------------------------------------
print("🔄 Checking circular dependencies...")
-- Redirect output to file
local oldPrint = print
local outputFile = io.open("audit/audit-circular.txt", "w")
if outputFile then
	print = function(...)
		local args = {...}
		for i, v in ipairs(args) do
			outputFile:write(tostring(v))
			if i < #args then outputFile:write("\t") end
		end
		outputFile:write("\n")
	end

	local success, cycles = analyzeDeps.analyzeDependencies(SRC_DIR)

	outputFile:close()
	print = oldPrint

	if success then
		print("   ✓ audit/audit-circular.txt (no cycles 🎉)")
	elseif cycles and #cycles > 0 then
		print("   ⚠️  audit/audit-circular.txt (" .. #cycles .. " circular dependencies found)")
	else
		print("   ⚠️  audit/audit-circular.txt (check results)")
	end
else
	print("   ❌ Failed to write audit/audit-circular.txt")
end

-- -------------------------------------------
-- 7. Project Structure Check
-- -------------------------------------------
print("📂 Checking project structure...")
if dirExists("sync") then
	-- sync/ is from old project with internal sync process - should migrate to src/
	local syncCount = findFiles("sync", "*.lua") + findFiles("sync", "*.luau")

	local structureMsg
	if dirExists("src") then
		local srcCount = findFiles("src", "*.lua") + findFiles("src", "*.luau")
		structureMsg = string.format(
			[[⚠️  Both 'src/' and 'sync/' directories found

'sync/' is from an old project that used an internal sync process.
With the TekneGame framework, 'src/' is the standard source directory.

File counts:
  src/  → %d files
  sync/ → %d files

Recommendation:
  - Migrate sync/ → src/
  - Remove sync/ after migration]],
			srcCount,
			syncCount
		)
	else
		structureMsg = string.format(
			[[⚠️  Using 'sync/' directory (%d files)

'sync/' is from an old project that used an internal sync process.
With the TekneGame framework, 'src/' is the standard source directory.

Recommendation:
  - Rename sync/ → src/
  - Update default.project.json to reference src/]],
			syncCount
		)
	end

	local file = io.open("audit/audit-structure.txt", "w")
	if file then
		file:write(structureMsg)
		file:close()
	end
	print("   ⚠️  audit/audit-structure.txt (sync/ is obsolete, migrate to src/)")
elseif dirExists("src") then
	print("   ✓ Project structure looks good (using src/)")
else
	print("   ✓ Project structure looks good")
end

-- -------------------------------------------
-- 8. File Extensions Analysis
-- -------------------------------------------
print("🔤 Analyzing file extensions...")
local luaCount = findFiles(SRC_DIR, "*.lua")
local luauCount = findFiles(SRC_DIR, "*.luau")
print(string.format("   📊 .lua: %d files, .luau: %d files", luaCount, luauCount))
if luaCount > 0 then
	print("   💡 Consider migrating .lua → .luau for better LSP support")
end

-- -------------------------------------------
-- 9. Dependency Graph Visualization
-- -------------------------------------------
print("🎨 Generating dependency graphs...")

if commandExists("dot") then
	-- Generate SVG and PNG versions
	local success1 = visualizeDeps.visualize(SRC_DIR, "audit/audit-graph.svg", "svg", false)
	local success2 = visualizeDeps.visualize(SRC_DIR, "audit/audit-graph.png", "png", false)

	if success1 then
		print("   ✓ audit/audit-graph.svg (grouped overview 🎉)")
		if success2 then
			print("   ✓ audit/audit-graph.png (PNG version)")
		end

		local dotFile = io.open("audit/audit-graph.dot", "r")
		if dotFile then
			dotFile:close()
			print("   ✓ audit/audit-graph.dot (source)")
		end
	else
		print("   ⚠️  Failed to generate grouped graph")
	end

	-- Generate detailed view
	local success3 = visualizeDeps.visualize(SRC_DIR, "audit/audit-graph-full.svg", "svg", true)
	local success4 = visualizeDeps.visualize(SRC_DIR, "audit/audit-graph-full.png", "png", true)

	if success3 then
		print("   ✓ audit/audit-graph-full.svg (detailed 🎉)")
		if success4 then
			print("   ✓ audit/audit-graph-full.png (PNG version)")
		end

		local fullDotFile = io.open("audit/audit-graph-full.dot", "r")
		if fullDotFile then
			fullDotFile:close()
			print("   ✓ audit/audit-graph-full.dot (source)")
		end
	else
		print("   ⚠️  Failed to generate detailed graph")
	end
elseif not commandExists("dot") then
	print("   ⏭️  Skipped (graphviz not installed)")
	if IS_WINDOWS then
		print("      💡 choco install graphviz")
	else
		print("      💡 brew install graphviz")
	end
else
	print("   ⏭️  Skipped")
end

-- -------------------------------------------
-- Summary
-- -------------------------------------------
print("")
print("===========================================")
print("✅ Audit complete!")
print("===========================================")
print("")
print("📁 Reports generated:")
exec(IS_WINDOWS and "dir audit" or "ls -lh audit | grep -v '^total' | grep -v '^d'")
print("")

print("📌 Next steps:")
print("   1. Review reports in audit/ directory")
print("   2. Fix critical issues (errors)")
print("   3. Address warnings as needed")
print("")

-- Count total issues
local totalIssues = 0
if io.open("audit/audit-check.txt", "r") then
	local typeErrors = grepCount("audit/audit-check.txt", "TypeError:")
	if typeErrors > 0 then
		print("   🔍 Type errors: " .. typeErrors)
		totalIssues = totalIssues + typeErrors
	end
	io.close(io.open("audit/audit-check.txt", "r"))
end

if io.open("audit/audit-selene.txt", "r") then
	local seleneWarnings = grepCount("audit/audit-selene.txt", "warning")
	if seleneWarnings > 0 then
		print("   🔎 Selene warnings: " .. seleneWarnings)
		totalIssues = totalIssues + seleneWarnings
	end
	io.close(io.open("audit/audit-selene.txt", "r"))
end

print("")
if totalIssues == 0 then
	print("🎉 No critical issues found!")
else
	print("⚠️  Total issues to review: " .. totalIssues)
end

print("")
print("💡 To auto-format code: stylua " .. SRC_DIR .. "/")
print("")
